### PR TITLE
MessageExtension: Corrected package descriptions causing invalid json content

### LINKED ISSUE #16: [Team's Messaging Extension search sample] Unexpected results when searching for any package
## Version
What package version of the SDK are you using.
- I'm using the Teams samples from main, so I'm using the local packages.

**Describe the bug**
- The query parameter value is always returning an empty string in the `OnTeamsMessagingExtensionQueryAsync` method in the line [35](https://github.com/microsoft/Agents-for-net/blob/main/src/samples/Teams/MessagingExtensionsSearch/Bots/TeamsMessagingExtensionsSearchBot.cs#L35)

**To Reproduce**
How can we reproduce this error?

- Follow the steps [here](https://github.com/microsoft/Agents-for-net/blob/main/src/samples/Teams/MessagingExtensionsSearch/README.md) to install the bot in Teams.
- In a chat with the bot in teams, select the bot from a list Image
- Write a package name
- The app won't recognize any text that is being passed as it is always returning an empty string.

Please provide Code Snippets, Channel type, and any special configuration we will need to reproduce this problem.

**Expected behavior**
- When writing a package name, return the package I'm looking for.

**Screenshots**
_Line with the issue_ 
Image

**Additional context**
I fixed it by changing the line to this:

`text = query?.Parameters?[0]?.Value.ToString() ?? string.Empty;`

### LINKED ISSUE #17: [Team's Messaging Extension search sample] Unexpected results when selecting a package without an icon
## Version
What package version of the SDK are you using.
- I'm using the Teams samples from main, so I'm using the local packages.

**Describe the bug**
- When selecting a result without an Icon, I get back the following message: _The given key was not present in the dictionary_

**To Reproduce**
How can we reproduce this error?

- Follow the steps [here](https://github.com/microsoft/Agents-for-net/blob/main/src/samples/Teams/MessagingExtensionsSearch/README.md) to install the bot in Teams.
- In a chat with the bot in teams, select the bot from this list Image
- Select a result without an Icon
- You will receive a _The given key was not present in the dictionary_ message

Please provide Code Snippets, Channel type, and any special configuration we will need to reproduce this problem.

**Expected behavior**
- When selecting a result without an Icon, it should work the same way it works with results with Icons.

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by tracyboehrer**
Fixes #16 
Fixes #17

### CODE REVIEW

File: src/samples/Teams/MessagingExtensionsSearch/Bots/TeamsMessagingExtensionsSearchBot.cs [hunk 1]
```diff
@@ -18,22 +18,17 @@
...
-    public class TeamsMessagingExtensionsSearchBot : TeamsActivityHandler
+    public class TeamsMessagingExtensionsSearchBot(IConfiguration config) : TeamsActivityHandler
     {
-        public readonly string _baseUrl;
-        public TeamsMessagingExtensionsSearchBot(IConfiguration config)
-        {
-            _baseUrl = config["BaseUrl"];
-
-        }
+        public readonly string _baseUrl = config["BaseUrl"];
```
Comment (MattB-msft) [inline src/samples/Teams/MessagingExtensionsSearch/Bots/TeamsMessagingExtensionsSearchBot.cs:23]: Is this entry documented? 
IE:  what is "BaseURL" ?

**Review by MattB-msft — APPROVED** [review]
